name: Deploy Application

on:
  push:
    path:
      - './assignment/'

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Az CLI login
        run: |
           az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

      - name: Update Azure CLI to the Latest Version
        run: |
          sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli
      
      - name: Get AKS Credentials 
        run: |
          az aks get-credentials --name "${{ secrets.MY_AKS_CLUSTER }}" --resource-group "${{ secrets.MY_RESOURCE_GROUP_NAME }}"
          kubectl config current-context

      - name: Docker Azure login
        uses: azure/docker-login@v1
        with: 
          login-server: projectimage01.azurecr.io
          username: $ACR_USERNAME
          password: $ACR_PASSWORD

      - name: Build AKS Cluster and Push Image
        run: |
          docker build --no-cache ./flask-app/ -t projectimage01.azurecr.io/notes-app:latest
          az acr login --name projectimage01
          az acr update --name projectimage01 --anonymous-pull-enabled true
          docker push projectimage01.azurecr.io/notes-app:latest


      - uses: azure/aks-set-context@v4
        with:
           resource-group: ${{ secrets.MY_RESOURCE_GROUP_NAME }}
           cluster-name: ${{ secrets.MY_AKS_CLUSTER }}

      - name: Deploy Application to AKS
        run: |
          cd k8s 
          kubectl apply -n assignment -f mysql-deployment.yml
          kubectl apply -n assignment -f mysql-configmap.yml
          kubectl apply -n assignment -f mysql-secrets.yml
          kubectl apply -n assignment -f mysql-svc.yml
          kubectl apply -n assignment -f two-tier-app-deployment.yml
          sleep 60
          kubectl apply -n assignment -f two-tier-app-svc.yml
          sleep 50
          kubectl get all -n assignment
          kubectl rollout restart deployment two-tier-app -n assingment