name: Deploy Application

on:
  push:
    path:
      - './django-notes/'

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Az CLI login
        run: |
           az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

      - name: Update Azure CLI to the Latest Version
        run: |
          sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli
      
      - name: Get AKS Credentials 
        run: |
          az aks get-credentials --name "${{ secrets.MY_AKS_CLUSTER }}" --resource-group "${{ secrets.MY_RESOURCE_GROUP_NAME }}"
          kubectl config current-context

      - name: Docker Azure login
        uses: azure/docker-login@v1
        with: 
          login-server: projectimage01.azurecr.io
          username: $ACR_USERNAME
          password: $ACR_PASSWORD

      - name: Build AKS Cluster and Push Image
        run: |
          docker build ./django-notes-app/ -t projectimage01.azurecr.io/notes-app:${{ github.sha }}
          az acr login --name projectimage01
          az acr update --name projectimage01 --anonymous-pull-enabled true
          docker push projectimage01.azurecr.io/notes-app:${{ github.sha }}

      - name: Fetch ACR Credentials
        id: fetch_credentials
        run: |
          ACR_USERNAME=$(terraform output username | tr -d '"')
          ACR_PASSWORD=$(terraform output password | tr -d '"')
          echo "Extracted ACR_USERNAME: $ACR_USERNAME" 
          echo "Extracted ACR_PASSWORD: $ACR_PASSWORD"



      - uses: azure/aks-set-context@v4
        with:
           resource-group: ${{ secrets.MY_RESOURCE_GROUP_NAME }}
           cluster-name: ${{ secrets.MY_AKS_CLUSTER }}

      - name: Deploy Application to AKS
        run: |
          kubectl apply -f django-notes.yaml
          