name: Create AKS Cluster with Terraform

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  AKS-Cluster-Deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: 'Az CLI login'
        run: |
          az login --tenant add67cd2-c8b2-416c-b171-b61b22be92f4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: latest

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Refresh Terraform State
        id: refresh
        run: terraform refresh

      - name: Terraform Plan
        id: plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve

      - name: Get AKS Cluster Name
        id: get_aks_name
        run: |
          AKS_CLUSTER_NAME=$(terraform output -raw aks_cluster_name)
          if [ -z "$AKS_CLUSTER_NAME" ]; then
            echo "Error: AKS Cluster Name is empty!"
            exit 1
          fi
          echo "AKS_CLUSTER_NAME=$AKS_CLUSTER_NAME" >> $GITHUB_ENV

      - name: Get Resource Group Name
        id: get_rg_name
        run: |
          RESOURCE_GROUP_NAME=$(terraform output -raw resource_group_name)
          if [ -z "$RESOURCE_GROUP_NAME" ]; then
            echo "Error: Resource Group Name is empty!"
            exit 1
          fi
          echo "RESOURCE_GROUP_NAME=$RESOURCE_GROUP_NAME" >> $GITHUB_ENV


      - name: Build AKS Cluster and Push Image
        run: |
          docker build -t notes-app ./django-notes-app/
          docker tag notes-app:latest projectimage01.azurecr.io/notes-app:latest
          az acr login --name projectimage01
          docker push projectimage01.azurecr.io/notes-app:latest

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --name "$AKS_CLUSTER_NAME" --resource-group "$RESOURCE_GROUP_NAME"

      - name: Deploy Application to AKS
        run: |
          kubectl apply -f django.notes.yaml
          kubectl get svc -n notes-app
